title: My Blog
description: Writings on software, engineering, and notes.
url: "https://jnguyenvt0104.github.io"
baseurl: ""
author:
  name: Your Name

markdown: kramdown
permalink: /:year/:month/:day/:title/
paginate: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
